[tool.pdm]

[build-system]
requires = ['pdm-backend']
build-backend = 'pdm.backend'

[project]
name = "organ"
version = "0.1.0"
description = ""
authors = [{ name = "foglabs", email = "henry_neels@wgbh.org" }]
dependencies = [
    "fastapi>=0.111.1",
    "uvicorn>=0.30.3",
    "sqlmodel>=0.0.21",
    "psycopg2>=2.9.9",
    "starlette-admin>=0.14.1",
    "itsdangerous>=2.2.0",
    "fastcrud>=0.13.1",
    "asyncpg>=0.29.0",
    "pydantic>=2.8.2",
]
requires-python = ">=3.9"
license = { text = "MIT" }
